export type SupportedLanguage = 'en' | 'de';

export interface LanguageSource {
  language?: string;
  locale?: {
    language?: string;
  };
}

const EN = {
  'card.description': 'Display your Parqet portfolio data — performance, holdings and activities.',
  'snapshot.name': 'Parqet Daily Snapshot',
  'snapshot.description': 'Per-holding daily P&L based on a custom snapshot time.',
  'views.performance': 'Performance',
  'views.holdings': 'Holdings',
  'views.activities': 'Activities',
  'views.layout': 'Layout',
  'editor.device': 'Portfolio (leave empty for auto-detect)',
  'editor.defaultView': 'Default View',
  'editor.defaultInterval': 'Default Interval',
  'editor.currencySymbol': 'Currency Symbol',
  'editor.holdingsLimit': 'Holdings Limit',
  'editor.activitiesLimit': 'Activities Limit',
  'editor.showIntervalSelector': 'Show Interval Selector',
  'editor.showPerformanceChart': 'Show Performance Chart',
  'editor.showAllocationChart': 'Show Allocation Chart',
  'editor.showLogo': 'Show Holding Logos',
  'editor.compact': 'Compact Mode',
  'editor.hideHeader': 'Hide Header',
  'interval.1d': '1 Day',
  'interval.1w': '1 Week',
  'interval.mtd': 'Month to Date',
  'interval.1m': '1 Month',
  'interval.3m': '3 Months',
  'interval.6m': '6 Months',
  'interval.1y': '1 Year',
  'interval.ytd': 'Year to Date',
  'interval.3y': '3 Years',
  'interval.5y': '5 Years',
  'interval.10y': '10 Years',
  'interval.max': 'Maximum',
  'interval.short.1d': '1D',
  'interval.short.1w': '1W',
  'interval.short.mtd': 'MTD',
  'interval.short.1m': '1M',
  'interval.short.3m': '3M',
  'interval.short.6m': '6M',
  'interval.short.1y': '1Y',
  'interval.short.ytd': 'YTD',
  'interval.short.3y': '3Y',
  'interval.short.5y': '5Y',
  'interval.short.10y': '10Y',
  'interval.short.max': 'Max',
  'common.loading': 'Loading',
  'common.noData': 'No data',
  'common.name': 'Name',
  'common.value': 'Value',
  'common.profitLoss': 'P&L',
  'common.profitLossPct': 'P&L%',
  'common.weight': 'Weight',
  'common.unknown': 'Unknown',
  'common.total': 'Total',
  'common.dividends': 'Dividends',
  'common.fees': 'Fees',
  'common.taxes': 'Taxes',
  'common.timeInterval': 'Time interval',
  'common.selectPortfolio': 'Select portfolio',
  'common.portfolioAllocationChart': 'Portfolio allocation chart',
  'card.allPortfolios': 'All Portfolios',
  'card.noPortfolios': 'No Parqet portfolios found',
  'card.addIntegration': 'Add the Parqet Companion integration first',
  'card.rateLimitWarning': 'API rate limit reached — wait a few minutes before retrying; reloading now makes it worse',
  'card.rateLimitError': 'Rate limit exceeded',
  'card.loadError': 'Failed to load data',
  'performance.totalValue': 'Total Value',
  'performance.xirr': 'XIRR',
  'performance.ttwror': 'TTWROR',
  'performance.unrealizedGain': 'Unrealized Gain',
  'performance.realizedGain': 'Realized Gain',
  'performance.unrealized': 'Unrealized',
  'performance.realized': 'Realized',
  'performance.noData': 'No data available.',
  'holdings.none': 'No holdings found.',
  'holdings.other': 'Other',
  'holdings.shares': 'Shares',
  'holdings.averagePrice': 'Avg Price',
  'holdings.current': 'Current',
  'activities.all': 'All',
  'activities.buy': 'Buy',
  'activities.sell': 'Sell',
  'activities.dividend': 'Dividend',
  'activities.interest': 'Interest',
  'activities.transferIn': 'Transfer In',
  'activities.transferOut': 'Transfer Out',
  'activities.feesTaxes': 'Fees/Taxes',
  'activities.deposit': 'Deposit',
  'activities.withdrawal': 'Withdrawal',
  'activities.rateLimit': 'API rate limit reached — data will refresh automatically',
  'activities.loadError': 'Failed to load activities',
  'activities.none': 'No activities found.',
  'activities.loadMore': 'Load more',
  'activities.tax': 'Tax',
  'activities.fee': 'Fee',
  'snapshot.compare': 'vs.',
  'snapshot.enable': 'Enable daily snapshots in integration settings.',
  'snapshot.loadError': 'Failed to load snapshot data',
  'snapshot.dailyProfitLoss': 'Daily P&L',
  'snapshot.waiting': 'Waiting for first daily snapshot.',
} as const;

export type TranslationKey = keyof typeof EN;

const DE: Record<TranslationKey, string> = {
  'card.description': 'Zeigt deine Parqet-Portfoliodaten mit Wertentwicklung, Positionen und Aktivitäten.',
  'snapshot.name': 'Parqet Tages-Snapshot',
  'snapshot.description': 'Täglicher Gewinn oder Verlust je Position auf Basis einer eigenen Snapshot-Zeit.',
  'views.performance': 'Wertentwicklung',
  'views.holdings': 'Positionen',
  'views.activities': 'Aktivitäten',
  'views.layout': 'Darstellung',
  'editor.device': 'Portfolio (leer lassen für automatische Erkennung)',
  'editor.defaultView': 'Standardansicht',
  'editor.defaultInterval': 'Standardzeitraum',
  'editor.currencySymbol': 'Währungssymbol',
  'editor.holdingsLimit': 'Maximale Positionen',
  'editor.activitiesLimit': 'Maximale Aktivitäten',
  'editor.showIntervalSelector': 'Zeitraumauswahl anzeigen',
  'editor.showPerformanceChart': 'Wertentwicklungsdiagramm anzeigen',
  'editor.showAllocationChart': 'Allokationsdiagramm anzeigen',
  'editor.showLogo': 'Logos der Positionen anzeigen',
  'editor.compact': 'Kompakte Darstellung',
  'editor.hideHeader': 'Kopfzeile ausblenden',
  'interval.1d': '1 Tag',
  'interval.1w': '1 Woche',
  'interval.mtd': 'Laufender Monat',
  'interval.1m': '1 Monat',
  'interval.3m': '3 Monate',
  'interval.6m': '6 Monate',
  'interval.1y': '1 Jahr',
  'interval.ytd': 'Laufendes Jahr',
  'interval.3y': '3 Jahre',
  'interval.5y': '5 Jahre',
  'interval.10y': '10 Jahre',
  'interval.max': 'Gesamt',
  'interval.short.1d': '1T',
  'interval.short.1w': '1W',
  'interval.short.mtd': 'MTD',
  'interval.short.1m': '1M',
  'interval.short.3m': '3M',
  'interval.short.6m': '6M',
  'interval.short.1y': '1J',
  'interval.short.ytd': 'YTD',
  'interval.short.3y': '3J',
  'interval.short.5y': '5J',
  'interval.short.10y': '10J',
  'interval.short.max': 'Max',
  'common.loading': 'Wird geladen',
  'common.noData': 'Keine Daten',
  'common.name': 'Name',
  'common.value': 'Wert',
  'common.profitLoss': 'G/V',
  'common.profitLossPct': 'G/V %',
  'common.weight': 'Anteil',
  'common.unknown': 'Unbekannt',
  'common.total': 'Gesamt',
  'common.dividends': 'Dividenden',
  'common.fees': 'Gebühren',
  'common.taxes': 'Steuern',
  'common.timeInterval': 'Zeitraum',
  'common.selectPortfolio': 'Portfolio auswählen',
  'common.portfolioAllocationChart': 'Diagramm zur Portfolioaufteilung',
  'card.allPortfolios': 'Alle Portfolios',
  'card.noPortfolios': 'Keine Parqet-Portfolios gefunden',
  'card.addIntegration': 'Füge zuerst die Parqet-Companion-Integration hinzu',
  'card.rateLimitWarning': 'API-Limit erreicht — warte einige Minuten; ein erneutes Laden verschärft das Problem',
  'card.rateLimitError': 'API-Limit überschritten',
  'card.loadError': 'Daten konnten nicht geladen werden',
  'performance.totalValue': 'Gesamtwert',
  'performance.xirr': 'XIRR',
  'performance.ttwror': 'TTWROR',
  'performance.unrealizedGain': 'Unrealisierter Gewinn',
  'performance.realizedGain': 'Realisierter Gewinn',
  'performance.unrealized': 'Unrealisiert',
  'performance.realized': 'Realisiert',
  'performance.noData': 'Keine Daten verfügbar.',
  'holdings.none': 'Keine Positionen gefunden.',
  'holdings.other': 'Sonstige',
  'holdings.shares': 'Anteile',
  'holdings.averagePrice': 'Ø Kaufpreis',
  'holdings.current': 'Aktuell',
  'activities.all': 'Alle',
  'activities.buy': 'Kauf',
  'activities.sell': 'Verkauf',
  'activities.dividend': 'Dividende',
  'activities.interest': 'Zinsen',
  'activities.transferIn': 'Übertrag Eingang',
  'activities.transferOut': 'Übertrag Ausgang',
  'activities.feesTaxes': 'Gebühren/Steuern',
  'activities.deposit': 'Einzahlung',
  'activities.withdrawal': 'Auszahlung',
  'activities.rateLimit': 'API-Limit erreicht — die Daten werden automatisch aktualisiert',
  'activities.loadError': 'Aktivitäten konnten nicht geladen werden',
  'activities.none': 'Keine Aktivitäten gefunden.',
  'activities.loadMore': 'Mehr laden',
  'activities.tax': 'Steuer',
  'activities.fee': 'Gebühr',
  'snapshot.compare': 'ggü.',
  'snapshot.enable': 'Aktiviere tägliche Snapshots in den Integrationseinstellungen.',
  'snapshot.loadError': 'Snapshot-Daten konnten nicht geladen werden',
  'snapshot.dailyProfitLoss': 'Tages-G/V',
  'snapshot.waiting': 'Warte auf den ersten täglichen Snapshot.',
};

export const TRANSLATIONS = { en: EN, de: DE } as const;

function rawLanguage(source?: LanguageSource | string): string {
  if (typeof source === 'string') return source;
  const fromHass = source?.locale?.language ?? source?.language;
  if (fromHass) return fromHass;
  if (typeof document !== 'undefined' && document.documentElement.lang) {
    return document.documentElement.lang;
  }
  if (typeof navigator !== 'undefined' && navigator.language) {
    return navigator.language;
  }
  return 'en';
}

export function languageFromHass(source?: LanguageSource | string): SupportedLanguage {
  return rawLanguage(source).toLowerCase().split(/[-_]/, 1)[0] === 'de' ? 'de' : 'en';
}

export function localeForHass(source?: LanguageSource | string): string {
  return languageFromHass(source) === 'de' ? 'de-DE' : 'en-US';
}

export function t(key: TranslationKey, source?: LanguageSource | string): string {
  return TRANSLATIONS[languageFromHass(source)][key];
}
